#!/usr/bin/ruby

# $Id$
# Copyright (c) 2008 Netomata, Inc.  All Rights Reserved. 
# Please review accompanying 'LICENSE' file or
# http://www.netomata.com/license_v1 for important notices,
# disclaimers, and license terms (GPL v2.0 or alternative).

require 'optparse'

# we delay requiring the 'netomata' libraries until after the command line
# arguments are parsed, so that the library location can be specified by a
# '-L' command line argument

$NETOMATA_LIB = "/usr/local/lib/netomata/lib"
if (ENV.key?("NETOMATA_LIB")) then
    $NETOMATA_LIB = ENV["NETOMATA_LIB"]
end

class NcgArguments < Hash
    def initialize(args)
	super()

	opts = OptionParser.new do |opts|
	    opts.banner = "Usage: #$0 [options]"
	    opts.on('-d', '--dump',
	    	'dump the fully-parsed data structure') do
		self[:dump] = true
	    end
	    opts.on('-D', '--debug', 'enable debug mode') do
		self[:debug] = true
		$debug = true
	    end
	    opts.on('-k', '--keys',
		'dump the list of keys') do
		self[:keys] = true
	    end
	    opts.on('-L', '--libdir', '=DIRNAME',
		    'specify Netomata library location (overrides NETOMATA_LIB envariable)') do |val|
		self[:libdir] = val
		$NETOMATA_LIB = val
	    end
	    opts.on('-v', '--verbose', 'enable verbose mode') do
		self[:verbose] = true
		$verbose = true
	    end
	    opts.on('-V', '--version', 'print version number') do
		# can't simply print the version number here yet,
		# because the Netomata libraries haven't been require'd yet,
		# because options need to be processed first,
		# because options might include '-L' to specify library location
		self[:version] = true
	    end
	    opts.on_tail('-h', '--help', 'display this help and exit') do
		puts opts
		exit
	    end
	end
	
	opts.parse!(args)
    end
end

# parse the command line arguments
args = NcgArguments.new(ARGV)

# push the NETOMATA_LIB location onto the load path, before requiring any
# Netomata-provided libraries
$LOAD_PATH.push($NETOMATA_LIB)
puts "NETOMATA_LIB=#{$NETOMATA_LIB}" if $verbose

# we delay requiring the 'netomata' libraries until here, so that the location
# of the libraries can be specified by a '-L' command line argument
require 'netomata'

if (args[:version]) then
    puts Netomata::Version
    exit
end

net = Netomata::Node.new

ARGV.each do |fn|
    net.import_file(open(fn),fn)
end

if (args[:keys]) then
    puts net.keys_r.join("\n")
    exit
end

if (args[:dump]) then
    pp net
    exit
end

# get the list of targets to generate config files for
net.keys_having_key("ncg_output").each { |target_key|
    puts "Generating #{net[target_key]["ncg_output"]} for #{target_key}" if $verbose
    unless template_filename = net[target_key]["ncg_template"] 
	raise "Target '#{target_key}' has 'ncg_output' key, but no 'ncg_template' key"
    end

    # set up shortcut "target" variable
    target = net[target_key]

    r = Netomata::Template::FromFile.new(template_filename).result_from_vars({
	"@net" => net,
        "@target_key" => target_key,
        "@target" => target
    })

    of = File.new(target["ncg_output"], "w")
    of.write(r)
    of.close
}
