# $Id$
# Copyright (c) 2008 Netomata, Inc.  All Rights Reserved. 
# Please review accompanying 'LICENSE' file or
# http://www.netomata.com/license_v1 for important notices,
# disclaimers, and license terms (GPL v2.0 or alternative).

cwd = Dir.getwd
ENV["NETOMATA_LIB"] = File.expand_path(File.join(File.dirname(__FILE__),"lib"))

require 'rake/testtask'

$svn_base_url="https://dev.netomata.com/svn/ncg"
$svn_trunk_url="#{$svn_base_url}/trunk"

def determine_svn_branch
    # URL: https://dev.netomata.com/svn/ncg/trunk	 => ""
    # URL: https://dev.netomata.com/svn/ncg/branch/brent => branch/brent
    branch = IO.popen("svn info").grep(/^URL:/)[0].chomp!
    branch.sub!("URL: #{$svn_base_url}/", "")
    if (branch.eql?("trunk")) then
	return ""
    else
	return branch
    end
end

def determine_svn_revision(rev=nil)
    if rev.nil? then
	cmd = "svn info"
    else
	cmd = "svn info -r #{rev}"
    end

    IO.popen(cmd).grep(/^Revision: /)[0].chomp!.split[1]
end

$svn_revision=determine_svn_revision()
$svn_branch=determine_svn_branch()
$svn_working_branch="branches/brent"

desc "Run all tests and generate/compare configs against baselines"
task "default" => ["test", "configs"]

lib_dir = File.expand_path('netomata')

desc "Run all tests"
task "test" => ["lib/netomata/version.rb", "do_test"]

Rake::TestTask.new("do_test") do |t|
    t.pattern = 'test/**/*.rb'
    t.libs = [lib_dir]
#   t.warning = true
end

desc "Generate test configs and diff against baseline"
task "configs" => ["lib/netomata/version.rb"] do
    sh 'rm -f sample/configs/switch-1.config sample/configs/switch-2.config'
    sh 'ncg -v sample/sample.neto'
    sh 'diff -u sample/configs/switch-1.baseline sample/configs/switch-1.config'
    sh 'diff -u sample/configs/switch-2.baseline sample/configs/switch-2.config'
    puts "Success!"
end

desc "Generate RDOC documentation"
task "rdoc" do
    sh 'rdoc -o rdoc lib/netomata.rb lib/netomata/'
end

desc "Check whether 'svn commit' or 'svn update' is needed"
task "svn_check" do
    puts "checking whether 'svn commit' or 'svn update' is needed..."
    unless IO.popen("svn status").readlines.length == 0
	fail ("#"*60 + "\n" +
	      "'svn status' is not clean; are there unchecked-in files?\n" +
	      "Need to do:\n\tsvn commit\n" +
	      "#"*60)
    end
    svn_info_rev = determine_svn_revision()
    svn_info_head_rev = determine_svn_revision("HEAD")
    unless (svn_info_rev == svn_info_head_rev)
	fail ("#"*60 + "\n" + 
	      "Version mismatch:\n" +
	      "\tsvn info\t\t=> #{svn_info_rev}\n" +
	      "\tsvn info -r HEAD\t=> #{svn_info_head_rev}\n" +
	      "Need to do:\n\tsvn update\n" +
	      "#"*60)
    end
end

desc "Snapshot current SVN trunk to demo tag"
task "tag_demo" => ["test", "configs", "svn_check"] do
    sh 'svn delete https://dev.netomata.com/svn/ncg/tags/demo -m "Removing old demo tag"'
    sh 'svn copy https://dev.netomata.com/svn/ncg/trunk https://dev.netomata.com/svn/ncg/tags/demo -m "Setting new demo tag"'
end

desc "Accept the current generated configs as the new baseline"
task "accept_baseline" => ["sample/configs/switch-1.config",
			    "sample/configs/switch-2.config"] do
    sh 'cp -p sample/configs/switch-1.config sample/configs/switch-1.baseline'
    sh 'cp -p sample/configs/switch-2.config sample/configs/switch-2.baseline'
end

dist_exclude_files = File.new("ignore.dist").readlines
dist_exclude_files.each { |l| l.chomp! }
dist_files = FileList['**/*']
dist_exclude_files.each { |e| dist_files.exclude(e) }
dist_files.exclude {|f| File.stat(f).directory? }

desc "Create a 'VERSION' file for distribution"
#task "VERSION" => ["svn_check"] do
task "VERSION" do
    puts "generating VERSION..."
    release = File.new("RELEASE").readline.chomp!
    v = File.new("VERSION", "w")
    v.truncate(0)
    if ($svn_branch.eql?("")) then
	v.puts("#{release}-#{$svn_revision}")
    else
	v.puts("#{release}-#{$svn_branch}-#{$svn_revision}")
    end
    v.close
end

desc "Create a 'lib/netomata/version.rb' file for distribution"
task "lib/netomata/version.rb" => ["VERSION"] do
    version = File.new("VERSION").readline.chomp!
    File.new("lib/netomata/version.rb", "w").print <<"EOF"
# Do not edit -- generated by Rakefile
class Netomata
        Version = "#{version}"
end
EOF
end

desc "Create all files for distribution"
task "dist" => ["dist_dir", "svn_check", "VERSION", "Manifest", "Versions", "dist_tar", "dist_tar_gz"]

desc "Clean out the dist directory"
task "dist_clean" do
    sh "rm -rf dist/*"
end

desc "Create 'dist' directory"
task "dist_dir" do
    if ! (File.exists?("dist") && File.directory?("dist")) then
	Dir.mkdir("dist")
    end
end 

desc "Create a 'tar' file for distribution"
task "dist_tar" => ["dist_dir", "VERSION", "Manifest"] do
    version = File.new("VERSION").readline.chomp!
    base = "ncg-#{version}"
    distbase = "dist/#{base}"
    sh "rm -f #{distbase}"
    sh "ln -s .. #{distbase}"
    sh "sed -e 's,^,#{base}/,' Manifest | tar chCfT dist #{distbase}.tar -"
end

desc "Create a 'tar.gz' file for distribution"
task "dist_tar_gz" => ["dist_dir", "dist_tar"] do
    version = File.new("VERSION").readline.chomp!
    base = "ncg-#{version}"
    distbase = "dist/#{base}"
    sh "gzip -c #{distbase}.tar > #{distbase}.tar.gz"
end

desc "Create Manifest"
task "Manifest" do
    puts "generating Manifest..."
    m = File.new("Manifest", "w")
    m.truncate(0)
    dist_files.sort.each { |l|
	m.puts(l)
    }
    m.close
end

desc "Create Versions"
task "Versions" do
    puts "generating Versions..."
    sh 'svn info > Versions'
    sh 'svn status -v >> Versions'
end

desc "Update svn:ignore property"
task "ignore.svn" do
    sh 'svn ps svn:ignore -F ignore.svn .'
    sh 'cd lib/netomata ; svn ps svn:ignore version.rb .'
end

desc "Merge changes from trunk into current branch"
task "merge_from_trunk" do
    if $svn_branch.eql?("") then
	fail("#"*60 + "\n" +
	      "'merge_from_trunk' can only be done when working in a branch\n" +
	      "#"*60)
    end
    sh "svn merge #{$svn_trunk_url}"
    sh "svn update"
    sh "svn status"
end

desc "Merge changes from current branch into trunk"
task "merge_to_trunk" => ["svn_check"] do
    if $svn_branch.eql?("") then
	fail("#"*60 + "\n" +
	      "'merge_to_trunk' can only be done when working in a branch\n" +
	      "#"*60)
    end
    sh "svn switch #{$svn_trunk_url}"
    sh "svn update"
    sh "svn merge --reintegrate #{$svn_base_url}/#{$svn_branch}"
    sh "svn update"
    puts "#"*60
    puts "####"
    puts "#### REMINDER: now working in trunk!"
    puts "####"
    puts "#"*60
    puts ""
    puts "Examine changes, then when ready to accept, do"
    puts "\tsvn commit -m 'Merge from #{$svn_branch} to trunk'"
    puts "\tsvn update"
    puts ""
    puts "#"*60
end

desc "Delete working branch"
task "delete_branch" do
    sh "svn delete #{$svn_base_url}/#{$svn_working_branch} -m 'Delete working branch'"
end

desc "Make working branch from trunk"
task "make_branch" do
    sh "svn copy #{$svn_trunk_url} #{$svn_base_url}/#{$svn_working_branch} -m 'Create working branch from trunk'"
end

desc "Switch from trunk to branch"
task "switch_to_branch" do
    sh "svn switch #{$svn_base_url}/#{$svn_working_branch}"
    sh "svn update"
end

desc "Delete old working branch, create new branch from trunk, and switch to branch"
task "branch" => ["delete_branch", "make_branch", "switch_to_branch"] do
    puts "#"*60
    puts "####"
    puts "#### Now working in #{$svn_working_branch}!"
    puts "####"
    puts "#"*60
end

desc "Diff working branch against trunk"
task "branch_diff" do
    sh "svn diff #{$svn_trunk_url} #{$svn_base_url}/#{$svn_working_branch}"
end
